import { Link } from "@tanstack/react-router";
import { ArrowUpRight, CalendarDays, Plus } from "lucide-react";
import { Button } from "@/components/ui/button";
import mascot from "@/assets/steer-mascot.png";
import { PageHeading, projects, StatusPill } from "./steer-ui";
import { t, useLocale } from "./steer-context";

export function ProjectList() {
  const { isArabic } = useLocale();
  return <><PageHeading eyebrow={t(isArabic, "Portfolio", "محفظة المشاريع")} title={t(isArabic, "Projects", "المشاريع")} description={t(isArabic, "Track the work that moves every project forward.", "تابع الأعمال التي تدفع كل مشروع إلى الأمام.")} action={<Button asChild size="lg"><Link to="/projects/new"><Plus/>{t(isArabic, "Create project", "إنشاء مشروع")}</Link></Button>}/><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{projects.map((project, index) => <Link key={project.id} to="/projects/$id" params={{ id: project.id }} className="group rounded-lg border border-border bg-card p-5 shadow-card transition hover:-translate-y-0.5 hover:border-primary/30 hover:shadow-card-hover"><div className="mb-8 flex items-start justify-between gap-3"><StatusPill tone={index === 1 ? "amber" : "green"}>{index === 1 ? t(isArabic, "At risk", "يحتاج متابعة") : t(isArabic, "On track", "حسب الخطة")}</StatusPill><ArrowUpRight className="size-5 text-muted-foreground transition-transform group-hover:-translate-y-0.5 group-hover:translate-x-0.5 rtl:rotate-[-90deg]"/></div><h2 className="font-display text-xl font-semibold text-foreground">{t(isArabic, project.name, project.ar)}</h2><p className="mt-1 text-sm text-muted-foreground">{t(isArabic, project.client, project.clientAr)}</p><div className="mt-6 h-1.5 overflow-hidden rounded-full bg-muted"><div className="h-full rounded-full bg-success" style={{ width: `${project.progress}%` }}/></div><div className="mt-3 flex items-center justify-between text-xs"><span className="font-semibold text-foreground">{project.progress}%</span><span className="flex items-center gap-1.5 text-muted-foreground"><CalendarDays className="size-3.5"/>{project.deadline}</span></div></Link>)}</div><section className="mt-7 flex items-center gap-5 rounded-lg border border-dashed border-border bg-surface px-5 py-4"><img src={mascot} alt="Steer construction assistant" loading="lazy" width={816} height={816} className="h-24 w-24 shrink-0 object-contain"/><div><h2 className="font-display text-lg font-semibold">{t(isArabic, "A clear start for every project", "بداية واضحة لكل مشروع")}</h2><p className="mt-1 text-sm text-muted-foreground">{t(isArabic, "When this portfolio is empty, your first project starts here.", "عندما تكون المحفظة فارغة، يبدأ مشروعك الأول من هنا.")}</p></div></section></>;
}
