import { Check, Copy, Link2, MoreHorizontal, RotateCcw, Send, UserRoundPlus } from "lucide-react";
import { Button } from "@/components/ui/button";
import { columns, StatusPill, tasks, Avatar } from "./steer-ui";
import { t, useLocale } from "./steer-context";

const priority = ["high","medium","low"] as const;

export function TaskBoard({ portfolio = false }: { portfolio?: boolean }) {
  const { isArabic } = useLocale();
  return <div className="w-full min-w-0 overflow-x-auto overscroll-x-contain pb-4"><div className="grid min-w-[1480px] grid-cols-7 gap-4">{columns.map((column,columnIndex)=><section key={column.key} className="min-h-[380px] rounded-2xl border border-border bg-board-column/60 p-3"><div className="sticky top-16 z-10 mb-3 flex min-h-10 items-center justify-between rounded-xl bg-card px-3 shadow-sm"><div className="flex items-center gap-2"><span className={`size-2 rounded-full ${column.tone==="green"?"bg-success":column.tone==="amber"?"bg-warning":"bg-info"}`}/><h3 className="text-xs font-bold text-foreground">{t(isArabic,column.en,column.ar)}</h3></div><span className="grid size-6 place-items-center rounded-full bg-muted text-xs font-semibold text-muted-foreground">1</span></div>{tasks.filter((task)=>task.status===column.key).map((task)=><article key={task.id} className="rounded-xl border border-border bg-card p-4 shadow-card transition-all duration-200 hover:-translate-y-0.5 hover:shadow-card-hover"><div className="mb-3 flex items-start justify-between gap-2"><StatusPill tone={priority[columnIndex%3]==="high"?"red":priority[columnIndex%3]==="medium"?"amber":"neutral"}>{t(isArabic,priority[columnIndex%3],priority[columnIndex%3]==="high"?"عالية":priority[columnIndex%3]==="medium"?"متوسطة":"منخفضة")}</StatusPill><Button variant="ghost" size="icon-sm" className="-me-2 -mt-2" aria-label="Task actions"><MoreHorizontal/></Button></div>{portfolio&&<p className="mb-2 text-xs font-semibold text-info">{t(isArabic,task.project,task.projectAr)}</p>}<h4 className="text-sm font-semibold leading-6 text-card-foreground">{t(isArabic,task.title,task.ar)}</h4><div className="mt-4 flex items-center justify-between"><StatusPill tone={column.tone}>{t(isArabic,task.due,task.dueAr)}</StatusPill><Avatar initials={task.owner}/></div>{column.key==="delegated"&&<div className="mt-3 flex items-center gap-1 rounded-[10px] border border-border bg-muted p-1 ps-2"><span className="min-w-0 flex-1 truncate text-[11px] text-info" dir="ltr">steer.app/t/8K2M</span><Button variant="ghost" size="icon-sm" aria-label="Copy task link"><Copy/></Button></div>}<div className="mt-3 flex items-center gap-1 border-t border-border pt-2"><Button variant="ghost" size="icon-sm" title={t(isArabic,"Move","نقل")}><Send/></Button>{column.key==="open"&&<Button variant="ghost" size="icon-sm" title={t(isArabic,"Delegate","تفويض")}><UserRoundPlus/></Button>}{column.key==="assignee"&&<Button variant="ghost" size="icon-sm" title={t(isArabic,"Confirm","تأكيد")}><Check/></Button>}{column.key==="done"&&<Button variant="ghost" size="icon-sm" title={t(isArabic,"Return","إعادة")}><RotateCcw/></Button>}{column.key==="delegated"&&<Link2 className="ms-auto size-3.5 text-info"/>}</div></article>)}</section>)}</div></div>;
}