import { Check, Copy, Link2, MoreHorizontal, RotateCcw, Send, UserRoundPlus } from "lucide-react";
import { Button } from "@/components/ui/button";
import { columns, StatusPill, tasks, Avatar } from "./steer-ui";
import { t, useLocale } from "./steer-context";

export function TaskBoard({ portfolio = false }: { portfolio?: boolean }) {
  const { isArabic } = useLocale();
  return <div className="overflow-x-auto pb-3"><div className="grid min-w-[1480px] grid-cols-7 gap-3">{columns.map((column) => <section key={column.key} className="min-h-[360px] rounded-lg border border-border bg-board-column p-3"><div className="mb-3 flex items-center justify-between"><div className="flex items-center gap-2"><span className="size-2 rounded-full bg-primary/35"/><h3 className="text-xs font-bold text-foreground">{t(isArabic, column.en, column.ar)}</h3></div><span className="text-xs text-muted-foreground">1</span></div>{tasks.filter((task) => task.status === column.key).map((task) => <article key={task.id} className="rounded-md border border-border bg-card p-3 shadow-card"><div className="mb-2 flex items-start justify-between gap-2">{portfolio && <span className="text-[10px] font-bold uppercase tracking-wide text-primary/65">{t(isArabic, task.project, task.projectAr)}</span>}<Button variant="ghost" size="icon-sm" className="-me-2 -mt-2" aria-label="Task actions"><MoreHorizontal/></Button></div><h4 className="text-sm font-semibold leading-5 text-card-foreground">{t(isArabic, task.title, task.ar)}</h4><div className="mt-3 flex items-center justify-between"><StatusPill tone={column.tone}>{t(isArabic, task.due, task.dueAr)}</StatusPill><Avatar initials={task.owner}/></div><div className="mt-3 flex items-center gap-1 border-t border-border pt-2"><Button variant="ghost" size="icon-sm" title={t(isArabic, "Move", "نقل")}><Send/></Button>{column.key === "open" && <Button variant="ghost" size="icon-sm" title={t(isArabic, "Delegate", "تفويض")}><UserRoundPlus/></Button>}{column.key === "assignee" && <Button variant="ghost" size="icon-sm" title={t(isArabic, "Confirm", "تأكيد")}><Check/></Button>}{column.key === "done" && <Button variant="ghost" size="icon-sm" title={t(isArabic, "Return", "إعادة")}><RotateCcw/></Button>}{column.key === "delegated" && <><Button variant="ghost" size="icon-sm" title={t(isArabic, "Copy link", "نسخ الرابط")}><Copy/></Button><Link2 className="ms-auto size-3.5 text-info"/></>}</div></article>)}</section>)}</div></div>;
}
