import { Link } from "@tanstack/react-router";
import { ArrowUpRight, CheckCircle2, Clock3, Copy, Link2, ShieldAlert, UserRoundCheck } from "lucide-react";
import { PageHeading, projects, StatusPill } from "./steer-ui";
import { t, useLocale } from "./steer-context";

const attention = [
 {tag:"Confirm",ar:"تأكيد",title:"Concrete cube results are ready",titleAr:"نتائج مكعبات الخرسانة جاهزة",project:"Riyadh Metro",tone:"green",Icon:UserRoundCheck},
 {tag:"Blocked",ar:"متعثرة",title:"Electrical room access not released",titleAr:"لم تتم إتاحة غرفة الكهرباء",project:"Office Tower",tone:"amber",Icon:ShieldAlert},
 {tag:"Overdue",ar:"متأخرة",title:"Drainage inspection response",titleAr:"رد فحص أعمال التصريف",project:"Al Noor Campus",tone:"red",Icon:Clock3},
 {tag:"Delegated",ar:"مفوّضة",title:"Field photos due by end of day",titleAr:"صور الموقع مطلوبة بنهاية اليوم",project:"Al Noor Campus",tone:"blue",Icon:Link2},
 {tag:"Waiting",ar:"بانتظار",title:"Façade sample consultant approval",titleAr:"اعتماد الاستشاري لعينة الواجهة",project:"Office Tower",tone:"amber",Icon:Clock3},
 {tag:"Duplicate",ar:"مكررة",title:"Two safety report tasks look similar",titleAr:"مهمتا تقرير السلامة تبدوان متشابهتين",project:"Riyadh Metro",tone:"neutral",Icon:Copy},
] as const;
export function TodayPanel(){const {isArabic}=useLocale();return <><PageHeading eyebrow={t(isArabic,"Thursday, 24 September","الخميس، ٢٤ سبتمبر")} title={t(isArabic,"Today","اليوم")} description={t(isArabic,"The decisions and follow-ups that need your attention now.","القرارات والمتابعات التي تحتاج انتباهك الآن.")}/><div className="grid gap-7 xl:grid-cols-[1.2fr_1fr]"><section><h2 className="mb-3 font-display text-xl font-semibold">{t(isArabic,"Attention","يحتاج انتباهك")}</h2><div className="overflow-hidden rounded-lg border border-border bg-card shadow-card">{attention.map((item,index)=><Link key={item.title} to="/projects/$id" params={{id:index%2?"campus":"metro"}} className="group flex min-h-20 items-center gap-4 border-b border-border px-4 last:border-0 hover:bg-secondary/45 sm:px-5"><span className="grid size-9 shrink-0 place-items-center rounded-full bg-secondary text-primary"><item.Icon className="size-4"/></span><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><StatusPill tone={item.tone}>{t(isArabic,item.tag,item.ar)}</StatusPill><span className="text-xs text-muted-foreground">{item.project}</span></div><p className="mt-1 truncate text-sm font-semibold">{t(isArabic,item.title,item.titleAr)}</p></div><ArrowUpRight className="size-4 text-muted-foreground"/></Link>)}</div></section><section><h2 className="mb-3 font-display text-xl font-semibold">{t(isArabic,"Project report","تقرير المشاريع")}</h2><div className="grid gap-3">{projects.map((project,index)=><article key={project.id} className="rounded-lg border border-border bg-card p-4 shadow-card"><div className="flex items-start justify-between"><div><h3 className="text-sm font-semibold">{t(isArabic,project.name,project.ar)}</h3><p className="mt-1 text-xs text-muted-foreground">{t(isArabic,project.client,project.clientAr)}</p></div><CheckCircle2 className="size-5 text-success"/></div><div className="mt-5 grid grid-cols-4 gap-2 text-center"><Metric label={t(isArabic,"Open","مفتوحة")} value={4+index}/><Metric label={t(isArabic,"Active","نشطة")} value={3-index}/><Metric label={t(isArabic,"Done","مكتملة")} value={12+index*4}/><Metric label={t(isArabic,"Blocked","متعثر")} value={index}/></div></article>)}</div></section></div></>}
function Metric({label,value}:{label:string;value:number}){return <div className="rounded-md bg-surface px-2 py-3"><b className="block font-display text-xl">{value}</b><span className="text-[10px] text-muted-foreground">{label}</span></div>}
